-----------------------
SELECT * FROM DISTRICT;
SELECT * FROM ACCOUNT;
SELECT * FROM TRANSACTIONS;
SELECT * FROM DISPOSITION;
SELECT * FROM CARD;
SELECT * FROM `ORDER`;
SELECT * FROM LOAN;
SELECT * FROM CLIENT;


----------------------------------------------------------------------------------
-- DATA CLEANING IN SNOWFLAKE


select max(`DATE`) FROM TRANSACTIONS;
select * from transactions;

SELECT * FROM CLIENT;

-- Add the AGE column if it doesn't exist
ALTER TABLE CLIENT ADD COLUMN IF NOT EXISTS AGE INTEGER;

-- Update age based on the maximum transaction year
UPDATE CLIENT c
SET AGE = datediff('year', c.BIRTH_DATE, max_date.max_date)
FROM (
    SELECT MAX(`DATE`) AS max_date 
    FROM TRANSACTIONS
) max_date
WHERE c.BIRTH_DATE IS NOT NULL;



SELECT * FROM TRANSACTIONS WHERE BANK IS NULL AND YEAR(`DATE`) = '2016';

SELECT YEAR(`DATE`), COUNT(*) AS TOT_TRXNS
FROM TRANSACTIONS
-- WHERE BANK IS NULL
GROUP BY 1
ORDER BY 1;


-- UPDATING YEAR IN DATE COLUMN IN TTRANSACTIONS TABLE

UPDATE TRANSACTIONS
SET `DATE` = DATEADD(year, 1, `DATE`)
WHERE YEAR(`DATE`) = 2021;

UPDATE TRANSACTIONS
SET `DATE` = DATEADD(year, 1, `DATE`)
WHERE YEAR(`DATE`) = 2020;

UPDATE TRANSACTIONS
SET `DATE` = DATEADD(year, 1, `DATE`)
WHERE YEAR(`DATE`) = 2019;

UPDATE TRANSACTIONS
SET `DATE` = DATEADD(year, 1, `DATE`)
WHERE YEAR(`DATE`) = 2018;

UPDATE TRANSACTIONS
SET `DATE` = DATEADD(year, 1, `DATE`)
WHERE YEAR(`DATE`) = 2017;

UPDATE TRANSACTIONS
SET `DATE` = DATEADD(year, 1, `DATE`)
WHERE YEAR(`DATE`) = 2016;

SELECT MIN(`DATE`),MAX(`DATE`) FROM TRANSACTIONS;

UPDATE TRANSACTIONS
SET BANK = 'Sky Bank'
WHERE BANK IS NULL AND YEAR(`DATE`) = 2022;

SELECT DISTINCT BANK FROM TRANSACTIONS WHERE YEAR(`DATE`) = 2022;

UPDATE TRANSACTIONS
SET BANK = 'DBS Bank'
WHERE BANK IS NULL AND YEAR(`DATE`) = 2021;

UPDATE TRANSACTIONS
SET BANK = 'Northern Bank'
WHERE BANK IS NULL AND YEAR(`DATE`) = 2019;

UPDATE TRANSACTIONS
SET BANK = 'Southern Bank'
WHERE BANK IS NULL AND YEAR(`DATE`) = 2018;

UPDATE TRANSACTIONS
SET BANK = 'ADB Bank'
WHERE BANK IS NULL AND YEAR(`DATE`) = 2017;

SELECT * FROM TRANSACTIONS WHERE BANK IS NULL AND YEAR(`DATE`) = 2017; -- change the year value to check your above update.

SELECT * FROM TRANSACTIONS WHERE BANK IS NULL;

SELECT * FROM CARD;
SELECT DISTINCT YEAR(ISSUED) FROM CARD
ORDER BY YEAR(ISSUED);